version: "3.7"
services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: canada-visa-tracker-pg
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
volumes:
  postgres:
